import { Node, Edge } from './types';

const NW = 112;
const NH = 114;
const CG = 52;
const RG = 28;
const c = (n: number) => n * (NW + CG);
const r = (n: number) => n * (NH + RG);

export const NODES: Node[] = [
  // ── POWER CHAIN ──────────────────────────────────────
  { id: "main_battery", name: "LV Battery", type: "power", stripe: "stripe-power",
    fullName: "12V Low Voltage Energy Storage System",
    duty: "System Base Power Supply",
    purpose: "Provides the primary 12V energy reservoir for the entire Low Voltage System, ensuring reliability for safety-critical indicators and logic.",
    procurement: 'bought',
    cost: 120, dims: "250×175×200mm", product: "12V AGM Battery (Fire Retardant Case)",
    desc: "Primary 12V LV power source. EV ONLY: must have fire retardant casing (T11.7.4) and comply with EV4.5.1. Must be within rollover envelope (T11.7.2).",
    pins: ["POS", "NEG"], img: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=12V+AGM+battery+fire+retardant",
    rules: ["T11.7.1", "T11.7.2", "T11.7.4", "T11.10.1", "EV4.5.1"], isNew: false,
    x: c(0), y: r(5), x3: 0, y3: 0.1, z3: 0.8 },

  { id: "lvms", name: "LVMS", type: "switch", stripe: "stripe-switch",
    fullName: "Low Voltage Master Switch",
    duty: "Global System Disconnect",
    purpose: "Manually disables all power to the LVS. Serves as the primary barrier for electrical safety during technical inspection (T11.3).",
    procurement: 'bought',
    cost: 30, dims: "60×60×80mm", product: "Rotary Disconnect Switch",
    desc: "FIXED: Rotary mechanical switch. Must be on RIGHT side of vehicle near main hoop. Red circular area ≥50mm diameter. Marked 'LV' + blue triangle red spark symbol. ON position = horizontal. T11.6.3: BSPD must be directly supplied from this switch.",
    pins: ["IN", "OUT"], img: "https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=battery+disconnect+rotary+switch",
    rules: ["T11.2.1", "T11.2.2", "T11.2.3", "T11.3.1", "T11.3.2", "T11.3.3", "T11.10.1"],
    isFixed: true, fixNote: "Relabelled as LVMS. Must have red circular marking and 'LV' label. Co-mounted with TSMS (T11.2.5).",
    x: c(1), y: r(5), x3: 0.35, y3: 0.5, z3: 0.15 },

  { id: "pdu", name: "PDU", type: "power", stripe: "stripe-power",
    fullName: "Power Distribution Unit & Logic Hub",
    duty: "Energy Distribution & Fuse Management",
    purpose: "Team-designed power management system. Handles fused 12V distribution and houses the isolated hardware relay for AIR control.",
    procurement: 'made',
    cost: 55, dims: "120×100×40mm", product: "Custom Power Distribution PCB",
    desc: "Centralized distribution. Must use NON-ORANGE LV wiring (T11.1.5). Features redundant thermal monitoring and direct SDC-to-AIR coil relay output stage. Grounded to chassis (T11.1.6).",
    pins: ["12V_IN", "GND", "FUSED_OUT_1", "FUSED_OUT_2", "AIR_COIL_OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=automotive+fuse+relay+box+12V",
    rules: ["A2.1.1", "T11.1.1", "T11.1.3", "T11.1.5", "T11.1.6", "T11.10.1", "EV3.2"],
    isFixed: true, fixNote: "AIR coil control relay added inside PDU. SDC output drives AIR relay coil directly.",
    x: c(2), y: r(5), x3: 0, y3: 0.4, z3: 0.2 },

  { id: "buck5v", name: "5V Automotive\nBuck Converter", type: "power", stripe: "stripe-power",
    fullName: "12V to 5V Step-Down Converter",
    duty: "Step-Down DC/DC Conversion",
    purpose: "Converts 12V LVS power into a regulated 5V rail to power microcontrollers and sensitive 5V analog sensors.",
    procurement: 'bought',
    cost: 25, dims: "60×30×22mm", product: "12V→5V 3A Automotive DC-DC",
    desc: "Regulated 5V supply for all LV electronics. NOTE: BSPD is now powered directly from LVMS, NOT from this converter (T11.6.3 fix).",
    pins: ["VIN+", "VIN-", "VOUT+", "VOUT-"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/detail/recom-power/R-78E5-0-0-5/4794212",
    rules: ["T11.1.2", "T11.10.1"],
    x: c(3), y: r(5), x3: 0, y3: 0.3, z3: 0.25 },

  // ── ECU ──────────────────────────────────────────────
  { id: "main_ecu", name: "Main ECU\n(STM32F405)", type: "mcu", stripe: "stripe-mcu",
    fullName: "Supervisory Vehicle Control Unit (VCU)",
    duty: "Logic Processing & Bus Management",
    purpose: "Main supervisory controller. Executes team-designed state machines, APPS plausibility algorithms, and CAN-based torque request logic.",
    procurement: 'made',
    cost: 55, dims: "110×85×20mm", product: "Team-Designed VCU (STM32F405-based PCB)",
    desc: "Central Logic Hub with 2x native CAN controllers. Handles data logging to SD card and RTD sequence. NOT in safety-critical SDC path. Features redundant watchdog timers for T11.9.4 compliance.",
    pins: ["5V", "3V3", "GND", "CANTX1", "CANRX1", "PA0-PA7", "PB0-PB11", "PC0-PC7"],
    img: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.st.com/en/microcontrollers-microprocessors/stm32f405-415.html",
    rules: ["A2.1.1", "A2.3.1", "T11.9.4", "T11.10.1"],
    isFixed: true, fixNote: "Upgraded to STM32F405 for hardware CAN support. F401 lacks native CAN peripherals.",
    x: c(5), y: r(5), x3: 0.2, y3: 0.5, z3: -0.2 },

  // ── CAN + DISPLAY ─────────────────────────────────────
  { id: "can_xcvr", name: "CAN Transceiver\nSN65HVD230", type: "module", stripe: "stripe-module",
    fullName: "Differential Bus Interface",
    duty: "Phys Layer Signal Conditioning",
    purpose: "Translates logic-level CAN TX/RX signals from the MCU into robust differential CANH/CANL signals for the vehicle bus.",
    procurement: 'bought',
    cost: 3, dims: "28×15×5mm", product: "SN65HVD230 CAN Module",
    desc: "3.3V CAN transceiver. Translates MCU TTL-CAN → Differential CAN. Must be terminated with 120Ω at the bus ends. Critical for T11.9.4 communications stability.",
    pins: ["VCC", "GND", "CTX", "CRX", "CANH", "CANL"],
    img: "https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/detail/texas-instruments/SN65HVD230D/2691880",
    rules: ["A2.1.1", "T11.9.4"],
    x: c(6), y: r(3), x3: 0.2, y3: 0.45, z3: -0.25 },

  { id: "driver_display", name: "CAN Dashboard\n(OLED/Nextion)", type: "display", stripe: "stripe-display",
    fullName: "Cockpit HMI Data Terminal",
    duty: "Real-time Telemetry Visualization",
    purpose: "Displays propulsion status and diagnostic alerts. Interfaces via CAN to minimize wiring bulk to the front of the vehicle.",
    procurement: 'made',
    cost: 45, dims: "110×60×12mm", product: "Team-Designed Dashboard Module",
    desc: "CAN-enabled dashboard. Displays speed, APPS%, and safety errors. Not safety-critical. Integrated 120Ω termination (selectable by jumper). Uses STM32/Arduino + CAN Transceiver.",
    pins: ["12V", "GND", "CANH", "CANL"],
    img: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A - Custom PCB",
    rules: ["T11.9.4"],
    x: c(7), y: r(3), x3: 0, y3: 0.7, z3: -0.5 },

  { id: "fl_wss", name: "FL Wheel Speed", type: "sensor", stripe: "stripe-sensor", cost: 15,
    fullName: "Front Left Hub Encoder",
    duty: "Angular Velocity Tracking",
    purpose: "Generates high-frequency digital pulses to calculate front-left wheel speed for precision odometry and slip control.",
    procurement: 'bought',
    dims: "50×15×15mm", product: "Hall Effect Gear Tooth Sensor",
    desc: "Front-left wheel speed. Digital pulse to ECU PA0.",
    pins: ["VCC", "GND", "OUT"], img: "https://images.unsplash.com/photo-1503694978374-8a2fa686963a?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+wheel+speed+sensor", rules: ["T11.10", "T11.10.1"],
    x: c(4), y: r(0), x3: -0.6, y3: 0.2, z3: -1.0 },
  { id: "fr_wss", name: "FR Wheel", type: "sensor", stripe: "stripe-sensor", cost: 15,
    fullName: "Front Right Wheel Speed",
    duty: "Angular Velocity Data Acquisition",
    purpose: "Provides high-frequency hall-effect digital pulses to the ECU to calculate vehicle speed and detect front-right traction loss.",
    procurement: 'bought',
    dims: "50×15×15mm", product: "Hall Effect Gear Tooth Sensor",
    desc: "Front-right wheel speed. Digital pulse to ECU PA1. Mounted at the hub assembly.",
    pins: ["VCC", "GND", "OUT"], img: "https://images.unsplash.com/photo-1503694978374-8a2fa686963a?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+wheel+speed+sensor", rules: ["T11.10", "T11.10.1"],
    x: c(4), y: r(1), x3: 0.6, y3: 0.2, z3: -1.0 },
  { id: "rl_wss", name: "RL Wheel Speed", type: "sensor", stripe: "stripe-sensor", cost: 15,
    fullName: "Rear Left Hub Encoder",
    duty: "Rotational Speed Sensing",
    purpose: "Measures rear-left hub rotation to provide data for traction management algorithms and general vehicle speed estimation.",
    procurement: 'bought',
    dims: "50×15×15mm", product: "Hall Effect Gear Tooth Sensor",
    desc: "Rear-left wheel speed. Digital pulse to ECU PA2.",
    pins: ["VCC", "GND", "OUT"], img: "https://images.unsplash.com/photo-1503694978374-8a2fa686963a?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+wheel+speed+sensor", rules: ["T11.10", "T11.10.1"],
    x: c(4), y: r(2), x3: -0.6, y3: 0.2, z3: 1.0 },
  { id: "rr_wss", name: "RR Wheel Speed", type: "sensor", stripe: "stripe-sensor", cost: 15,
    fullName: "Rear Right Hub Encoder",
    duty: "Rotational Speed Sensing",
    purpose: "Measures rear-right hub rotation for ground speed calculation and dynamic torque monitoring.",
    procurement: 'bought',
    dims: "50×15×15mm", product: "Hall Effect Gear Tooth Sensor",
    desc: "Rear-right wheel speed. Digital pulse to ECU PA3.",
    pins: ["VCC", "GND", "OUT"], img: "https://images.unsplash.com/photo-1503694978374-8a2fa686963a?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+wheel+speed+sensor", rules: ["T11.10", "T11.10.1"],
    x: c(4), y: r(3), x3: 0.6, y3: 0.2, z3: 1.0 },

  { id: "apps1", name: "APPS Sensor 1\n(Throttle)", type: "sensor", stripe: "stripe-sensor",
    fullName: "Pedal Position Encoder (A)",
    duty: "Primary Torque Request Input",
    purpose: "Converts the driver's throttle pedal displacement into a safety-critical analog signal for motor torque control.",
    procurement: 'bought',
    cost: 20, dims: "40×40×30mm", product: "Linear Hall Sensor / Pot (Transfer Fn A)",
    desc: "NEW: Accelerator Pedal Position Sensor 1. Analog signal to ECU PA4. Must have a DIFFERENT non-intersecting transfer function from APPS2. SCS signal: open/short must result in safe state (motor torque = 0). T11.8.5.",
    pins: ["VCC", "GND", "OUT_A"], img: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+linear+throttle+sensor",
    rules: ["T11.8.5", "T11.8.6", "T11.8.7", "T11.9", "T11.10.1"], isNew: true,
    newNote: "Mandatory for EV. 2 sensors required with different transfer functions.",
    x: c(4), y: r(4), x3: 0.2, y3: 0.1, z3: -0.7 },

  { id: "apps2", name: "APPS Sensor 2\n(Throttle)", type: "sensor", stripe: "stripe-sensor",
    fullName: "Pedal Position Encoder (B)",
    duty: "Redundant Plausibility Input",
    purpose: "Provides a secondary independent pedal signal with a non-intersecting transfer function to satisfy Rule T11.8 safety checks.",
    procurement: 'bought',
    cost: 20, dims: "40×40×30mm", product: "Linear Hall Sensor / Pot (Transfer Fn B)",
    desc: "NEW: Accelerator Pedal Position Sensor 2. Analog signal to ECU PA5. Different transfer function from APPS1. Implausibility >10% deviation for >100ms must cut motor torque immediately.",
    pins: ["VCC", "GND", "OUT_B"], img: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=hall+effect+linear+throttle+sensor",
    rules: ["T11.8.5", "T11.8.6", "T11.8.7", "T11.9", "T11.10.1"], isNew: true,
    newNote: "Must share pedal housing with APPS1. Different transfer function required.",
    x: c(4), y: r(5) + 5, x3: 0.25, y3: 0.1, z3: -0.7 },

  { id: "steer_sensor", name: "Steering Angle\nSensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Rack & Pinion Position Tracker",
    duty: "Lateral Dynamics Acquisition",
    purpose: "Tracks steering column rotation to enable aero-dynamic load calculations and future torque vectoring algorithms.",
    procurement: 'bought',
    cost: 20, dims: "40×40×30mm", product: "Analog Rotary Potentiometer",
    desc: "Measures steering wheel angle. Analog to ECU PA6. If used for torque vectoring, becomes SCS signal.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=automotive+steering+angle+sensor",
    rules: ["T11.10"], x: c(6), y: r(5), x3: 0, y3: 0.6, z3: -0.6 },

  { id: "fbps", name: "Front Brake\nPressure Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Front Circuit Hydraulic Transducer",
    duty: "Hydraulic Load Monitoring",
    purpose: "Measures front circuit brake pressure for BSPD plausibility checks and brake-light activation logic.",
    procurement: 'bought',
    cost: 60, dims: "80×25×25mm", product: "0-1500psi Pressure Transducer",
    desc: "Measures front hydraulic brake pressure. Analog to ECU PA7 AND direct to BSPD BPS_IN via a dedicated hardware-only tap (no shared software routing). Threshold ≥30 bar for hard braking detection. Must be separately disconnectable for tech inspection.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=brake+pressure+sensor+automotive",
    rules: ["T11.6.4", "T11.6.5", "T11.6.7", "T11.9", "T11.10.1"],
    x: c(6), y: r(6), x3: 0, y3: 0.2, z3: -0.7 },

  { id: "rbps", name: "Rear Brake\nPressure Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Rear Circuit Hydraulic Transducer",
    duty: "Bias Monitoring & Validation",
    purpose: "Captures rear circuit pressure to verify brake bias and provide redundancy for the front pressure circuit data.",
    procurement: 'bought',
    cost: 60, dims: "80×25×25mm", product: "0-1500psi Pressure Transducer",
    desc: "Measures rear hydraulic brake pressure. Analog to ECU PB0.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=brake+pressure+sensor+automotive",
    rules: ["T11.10", "T11.10.1"], x: c(6), y: r(7), x3: 0, y3: 0.2, z3: 0.7 },

  { id: "fl_susp", name: "FL Suspension\nTravel Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Front Left Potentiometric Slider",
    duty: "Suspension State Observation",
    purpose: "Tracks wheel travel relative to the chassis to analyze pitch, roll, and dampers frequency response.",
    procurement: 'bought',
    cost: 40, dims: "150×15×15mm", product: "Linear Potentiometer",
    desc: "Front-left suspension displacement. Analog to ECU PB1.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=linear+potentiometer+sensor",
    rules: ["T11.10", "T11.10.1"], x: c(7), y: r(5), x3: -0.5, y3: 0.3, z3: -0.9 },
  { id: "fr_susp", name: "FR Suspension\nTravel Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Front Right Potentiometric Slider",
    duty: "Suspension State Observation",
    purpose: "Provides live displacement data to the ECU for aero-mapping and chassis load distribution analysis.",
    procurement: 'bought',
    cost: 40, dims: "150×15×15mm", product: "Linear Potentiometer",
    desc: "Front-right suspension displacement. Analog to ECU PB2.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=linear+potentiometer+sensor",
    rules: ["T11.10", "T11.10.1"], x: c(7), y: r(6), x3: 0.5, y3: 0.3, z3: -0.9 },
  { id: "rl_susp", name: "RL Suspension\nTravel Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Rear Left Potentiometric Slider",
    duty: "Suspension State Observation",
    purpose: "Monitoring rear-left corner loads to evaluate tire contact patches and mechanical grip levels.",
    procurement: 'bought',
    cost: 40, dims: "150×15×15mm", product: "Linear Potentiometer",
    desc: "Rear-left suspension displacement. Analog to ECU PB3.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=linear+potentiometer+sensor",
    rules: ["T11.10", "T11.10.1"], x: c(7), y: r(7), x3: -0.5, y3: 0.3, z3: 0.9 },
  { id: "rr_susp", name: "RR Suspension\nTravel Sensor", type: "sensor", stripe: "stripe-sensor",
    fullName: "Rear Right Potentiometric Slider",
    duty: "Suspension State Observation",
    purpose: "Completes the 4-corner chassis measurement system for comprehensive vehicle dynamic modelling.",
    procurement: 'bought',
    cost: 40, dims: "150×15×15mm", product: "Linear Potentiometer",
    desc: "Rear-right suspension displacement. Analog to ECU PC0.",
    pins: ["VCC", "GND", "ANALOG_OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/result?keywords=linear+potentiometer+sensor",
    rules: ["T11.10", "T11.10.1"], x: c(7), y: r(8), x3: 0.5, y3: 0.3, z3: 0.9 },

  { id: "pedal_box", name: "Pedal Assembly\n(APPS & Brake)", type: "actuator", stripe: "stripe-new",
    fullName: "Driver Interface Mechanical Rack",
    duty: "Analog Input Modulation",
    purpose: "Team-designed mechanical assembly for throttle and brake actuation (T11.8.4, T6.1.11).",
    procurement: 'made',
    cost: 85, dims: "300×150×200mm", product: "Custom Aluminum/Steel Pedal Box",
    desc: "Student fabricated assembly. Features dual APPS sensors (T11.8.5) and mechanical redundant return springs (T11.8.4). Brake pedal designed to withstand 2kN (T6.1.10). Mounts pressure sensors directly.",
    pins: ["THROTTLE", "BRAKE", "GND"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A - Custom Fabrication",
    rules: ["A2.1.1", "T11.8.2", "T11.8.4", "T6.1.10", "T6.1.11"],
    x: c(3), y: r(4), x3: 0.2, y3: 0.2, z3: -0.8 },

  { id: "lv_harness", name: "LV Wiring Harness\n(Main Loom)", type: "module", stripe: "stripe-new",
    fullName: "Total System Neural Network",
    duty: "Signal & Power Interconnect",
    purpose: "Team-designed and manufactured electrical loom connecting all LV nodes (A2.1.1).",
    procurement: 'made',
    cost: 250, dims: "Multi-point distribution", product: "Custom Raychem/DR-25 Loom",
    desc: "Manufactured by students. Complies with T11.1.5 (non-orange) and EV4.5.6 (professional standards). Includes strain relief and moisture protection (EV4.5.4). Point-to-point continuity verified.",
    pins: ["ALL_TS_INTERLOCKS", "LV_PWR_RAILS", "CAN_DOMAINS"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A - Custom Assembly",
    rules: ["A2.1.1", "EV4.5.6", "EV4.5.7", "T11.1.5", "EV4.5.3", "EV3.1"],
    x: c(0), y: r(7), x3: 0, y3: 0.5, z3: 0 },

  { id: "ts_current", name: "TS Current Sensor\n(BSPD)", type: "sensor", stripe: "stripe-safety",
    fullName: "High-Voltage Ammeter Transfomer",
    duty: "Safety Load Monitoring",
    purpose: "Feeds the real-time Tractive System current profile directly into the BSPD hardware path (bypass ECU).",
    procurement: 'bought',
    cost: 35, dims: "48×48×21mm", product: "LEM HASS 50-S",
    desc: "Hall effect current sensor for BSPD. Measures TS motor current. Threshold set for ≤5kW at max TS voltage. Analog output directly to BSPD (not through ECU). Must be separately disconnectable.",
    pins: ["VCC", "GND", "OUT"],
    img: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.lem.com/en/hass-s",
    rules: ["T11.6.4", "T11.6.6", "T11.6.7"],
    x: c(5), y: r(7), x3: 0, y3: 0.2, z3: 1.2 },

  // ── SAFETY CHAIN ─────────────────────────────────────
  { id: "bspd", name: "BSPD Module", type: "safety", stripe: "stripe-safety",
    fullName: "Brake-System Plausibility Device",
    duty: "Hard-Brake Power Interlock",
    purpose: "The most complex custom-build block in the LVS. Non-programmable standalone hardware that opens SDC during high-power braking (Rule T11.6).",
    procurement: 'made',
    cost: 50, dims: "80×60×25mm", product: "Team-Designed Analog Logic PCB",
    desc: "PCB must be standalone with no other functionality, non-programmable, and directly supplied from LVMS. Latching behaviour (SDC stays open until LVMS power-cycle, or auto-resets only after implausibility clears for >10 s) must be implemented in pure analog/discrete logic per T11.6. Sensors (BPS/Current) must be directly connected with no shared routing.",
    pins: ["LV_IN_FROM_LVMS", "GND", "BPS_IN", "CURRENT_IN", "SDC_OUT"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A - Custom PCB",
    rules: ["A2.1.1", "A2.3.1", "T11.6.1", "T11.6.3", "T11.6.4", "T11.6.5", "T11.6.6", "T11.10.1"],
    isFixed: true, fixNote: "Power supply changed from 5V buck → direct LVMS supply. Sensor inputs now bypass ECU.",
    x: c(5), y: r(6), x3: 0.3, y3: 0.4, z3: 0.15 },

  { id: "imd", name: "IMD Module\n(Bender iso165C-1)", type: "safety", stripe: "stripe-safety",
    fullName: "Isolation Monitoring Device",
    duty: "HV-LV Chassis Continuity Check",
    purpose: "Monitors the insulation integrity between the Tractive System and the chassis to prevent lethal shock risks.",
    procurement: 'bought',
    cost: 350, dims: "72×54×67mm", product: "Bender ISOMETER iso165C-1",
    desc: "CORRECTED: IMD checks for high-voltage isolation leaks to chassis. If a leak is found, it must physically open the Shutdown Circuit (SDC) completely on its own, without relying on any MCU or AMS. It also features a secondary diagnostic line back to the AMS to log and signal the fault post-trip. Response value ≥500Ω/V.",
    pins: ["LV_IN", "GND", "SDA", "SCL", "SDC_OUT_HW", "GND_MEAS_1", "GND_MEAS_2"],
    img: "https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.bender.de/products/insulation-monitoring/isometer/iso165c",
    rules: ["A2.3.1", "EV6.3.1", "EV6.3.2", "EV6.3.3", "EV6.3.5", "EV6.3.6", "EV6.3.7", "T11.10.1"],
    isFixed: true, fixNote: "SDC_OUT now goes directly to hardware SDC chain. IMD fault indicator driven by IMD hardware directly.",
    x: c(5), y: r(8), x3: -0.2, y3: 0.1, z3: 0.7 },

  { id: "ams", name: "AMS\n(Accumulator Mgmt)", type: "safety", stripe: "stripe-safety",
    fullName: "Accumulator Management System (BMS)",
    duty: "Cell Life & Health Supervision",
    purpose: "Monitors internal cell voltages and temperatures to ensure the battery operates within safe Li-ion structural limits.",
    procurement: 'made',
    cost: 150, dims: "100×80×30mm", product: "Custom AMS PCB (Inside TSAC)",
    desc: "NEW: Mandatory for all EV. Monitors cell health and can open SDC internally. To comply with safety mandates, AMS acts as an independent safety link in the hardware loop, and does not control the IMD or TSMS switches. Diagnostic lines receive state indicators from neighboring modules.",
    pins: ["LV_IN", "GND", "CELL_V_BUS", "TEMP_INPUTS", "SDC_OUT_HW", "CAN_H", "CAN_L"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.ti.com/product/BQ76952",
    rules: ["A2.1.1", "A2.3.1", "EV5.8.1", "EV5.8.2", "EV5.8.3", "EV5.8.7", "EV5.8.9", "EV6.1.2", "T11.10.1"],
    isNew: true, newNote: "Mandatory EV component. Inside TSAC. Has own non-programmable SDC power stage.",
    x: c(5), y: r(9), x3: 0, y3: 0.3, z3: 1.2 },

  // ── SHUTDOWN CIRCUIT COMPONENTS ───────────────────────
  { id: "tsms", name: "TSMS\n(TS Master Switch)", type: "switch", stripe: "stripe-switch",
    fullName: "High Voltage Primary Isolator",
    duty: "Positive TS Rail Disconnect",
    purpose: "Provides the external, high-visibility manual interface for isolating the Tractive System from the powertrain.",
    procurement: 'bought',
    cost: 40, dims: "60×60×80mm", product: "TE Connectivity 3-1825138-0 (Rotary)",
    desc: "CORRECTED: Heavy rotary mechanical switch mounted on the side of the car. Rather than sending digital data to the AMS computer, it sits as a physical mechanical contact directly in the low-voltage SDC chain and/or on high-voltage lines. This prevents logical or software failure from closing the AIRs.",
    pins: ["IN", "OUT"],
    img: "https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.te.com/usa-en/product-3-1825138-0.html",
    rules: ["EV6.2.1", "EV6.2.2", "EV6.2.3", "EV6.2.4", "T11.2.5"],
    isFixed: true, fixNote: "Orange marking, lockout/tagout, mounted adjacent to LVMS.",
    x: c(1), y: r(7), x3: 0.35, y3: 0.6, z3: 0.15 },

  { id: "e_stop_cockpit", name: "Cockpit E-Stop\nButton", type: "switch", stripe: "stripe-switch",
    fullName: "Driver Emergency Disconnect",
    duty: "Immediate SDC Termination",
    purpose: "Provides the driver with a large, accessible mechanical button to instantly isolate all high-voltage power.",
    procurement: 'bought',
    cost: 15, dims: "24×24×50mm", product: "APEM A01ES-H (Push-Rotate)",
    desc: "Cockpit E-Stop. Push-pull or push-rotate type. Red button. Must be alongside steering wheel, unobstructed. Labeled with red spark on white-edged blue triangle. AUDIT: Verified normally-closed (NC) behavior. Direct-acting on SDC chain.",
    pins: ["IN", "OUT"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.apem.com/us/a01-812.html",
    rules: ["T11.4.4", "T11.4.2", "T11.4.7", "T11.10.1"],
    x: c(1), y: r(8), x3: 0.25, y3: 0.7, z3: -0.4 },

  { id: "e_stop_ext_l", name: "External E-Stop\n(Left Side)", type: "switch", stripe: "stripe-switch",
    fullName: "Side-Panel Emergency Killswitch (L)",
    duty: "Rescue Personal SDC Intercept",
    purpose: "Allows track-side marshals to safely shut down the vehicle from the left side in case of driver incapacitation.",
    procurement: 'bought',
    cost: 10, dims: "40×40×70mm", product: "TE Connectivity 1-1437580-1",
    desc: "Left-side external shutdown button. Behind driver compartment. Min 40mm diameter. Red. Labeled with red spark on white-edged blue triangle (T11.4.5). AUDIT: Verified reachable from outside vehicle by marshals.",
    pins: ["IN", "OUT"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.te.com/usa-en/product-1-1437580-1.html",
    rules: ["T11.4.3", "T11.4.2", "T11.4.7"],
    x: c(1), y: r(9), x3: -0.4, y3: 0.6, z3: 0.1 },

  { id: "e_stop_ext_r", name: "External E-Stop\n(Right Side)", type: "switch", stripe: "stripe-switch",
    fullName: "Side-Panel Emergency Killswitch (R)",
    duty: "Rescue Personal SDC Intercept",
    purpose: "Allows track-side marshals to safely shut down the vehicle from the right side for global safety compliance.",
    procurement: 'bought',
    cost: 10, dims: "40×40×70mm", product: "TE Connectivity 1-1437580-1",
    desc: "Right-side external shutdown button. Behind driver compartment. Min 40mm diameter. Red. Labeled with red spark on white-edged blue triangle. AUDIT: Mirror of Left-side E-Stop. Verified NC contact state.",
    pins: ["IN", "OUT"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.te.com/usa-en/product-1-1437580-1.html",
    rules: ["T11.4.3", "T11.4.2", "T11.4.7"],
    x: c(2), y: r(9), x3: 0.4, y3: 0.6, z3: 0.1 },

  { id: "inertia", name: "Inertia Switch\n(Mechanical)", type: "safety", stripe: "stripe-safety",
    fullName: "Collisions-Activated Shutoff",
    duty: "G-Force Impact Detection",
    purpose: "Opens the SDC automatically during severe impact or rollover to mitigate electrical fire risk post-crash.",
    procurement: 'bought',
    cost: 25, dims: "50×50×40mm", product: "OBD Inertia Switch (Semiconductor-Free)",
    desc: "Triggers at ≤8g peak for half-sine ≥50ms (T11.5.2). MUST NOT contain semiconductor components (T11.5.3). Purely mechanical ball-and-contact type. Direct-acting — no external relay (T11.5.5). Latches until manually reset.",
    pins: ["IN", "OUT"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.sensata.com/products/switches-sensors/crash-sensors",
    rules: ["T11.5.1", "T11.5.2", "T11.5.3", "T11.5.5", "T11.10.1"],
    isFixed: true, fixNote: "Must be verified semiconductor-free. Purely mechanical type.",
    x: c(1), y: r(10), x3: 0, y3: 0.2, z3: 0 },

  { id: "bots", name: "BOTS\n(Brake Over-Travel)", type: "safety", stripe: "stripe-safety",
    fullName: "Brake Fluid Loss Protector",
    duty: "Pedal Reach Limit Sensing",
    purpose: "Trips the SDC if the brake pedal over-travels, warning that the hydraulic circuit has likely developed a leak.",
    procurement: 'bought',
    cost: 5, dims: "28×16×10mm", product: "Honeywell V15T16-CZ100A05",
    desc: "Opens SDC on brake pedal over-travel (T6.2.1). Push-pull, push-rotate, or flip (T6.2.3). Repeated actuation must NOT close SDC (T6.2.2). Part of EV6.1.2 required SDC chain.",
    pins: ["COM", "NO", "NC"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/detail/honeywell-sensing-and-productivity-solutions/V15T16-CZ100A05/2418512",
    rules: ["T6.2.1", "T6.2.2", "T6.2.3", "EV6.1.2"],
    x: c(2), y: r(10), x3: 0, y3: 0.1, z3: -0.75 },

  // ── NEW COMPONENTS ────────────────────────────────────
  { id: "airs", name: "AIRs + Pre-charge\n(Inside TSAC)", type: "safety", stripe: "stripe-new",
    fullName: "Accumulator Isolation Contactors",
    duty: "High-Current Galvanic Isolation",
    purpose: "Physically connects/disconnects the high-voltage battery stack from the power bus under SDC control.",
    procurement: 'bought',
    cost: 120, dims: "80×60×40mm (per relay)", product: "Tyco EV200 Normally-Open Contactors (×2) + Pre-charge Relay",
    desc: "NEW: Mandatory. Two Accumulator Isolation Relays (pos + neg pole) inside TSAC. Normally-open mechanical relays. Pre-charge relay ensures DC-link caps reach 95% of TS voltage before closing 2nd AIR. SDC current drives AIR coils — when SDC opens, AIRs open. TSAC voltage indicator required. AUDIT: Galvanic isolation rated for 600V peak.",
    pins: ["COIL+", "COIL-", "HV_IN", "HV_OUT"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.te.com/usa-en/product-EV200AAANA.html",
    rules: ["A2.3.1", "EV5.6.1", "EV5.6.2", "EV5.6.3", "EV5.7.1", "EV5.7.2", "EV6.1.1", "T11.10.1"],
    isNew: true, newNote: "AIR coils driven by SDC current via PDU relay. When SDC opens → AIRs open → TS disconnected.",
    x: c(3), y: r(7), x3: 0, y3: 0.4, z3: 1.1 },

  { id: "hvd", name: "HVD\n(High Voltage Disconnect)", type: "safety", stripe: "stripe-new",
    fullName: "Manual Service Connector",
    duty: "Tool-Free System Isolation",
    purpose: "Allows technicians to safely remove the high-voltage link for maintenance or emergency pack isolation.",
    procurement: 'bought',
    cost: 40, dims: "Manual plug or fuse", product: "Manual Service Disconnect / HV Fuse Holder",
    desc: "NEW: Manually accessible disconnect for TS accumulator. Accessible without bodywork removal. Above 350mm from ground. Labeled 'HVD'. No tools required. ESO must remove within 10s. Includes connector interlock in SDC (EV4.5.10). Dummy connector on pushbar when not in use.",
    pins: ["HV_IN", "HV_OUT", "INTERLOCK"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.ixysic.com/home/pdfs.nsf/www/CPC1705Y.pdf",
    rules: ["A2.3.1", "EV4.8.1", "EV4.8.2", "EV4.8.4", "EV4.8.5", "EV4.5.10", "T11.10.1"],
    isNew: true, newNote: "Interlock wire routed into SDC. Opening HVD opens SDC interlock.",
    x: c(2), y: r(7), x3: 0, y3: 0.6, z3: 1.3 },

  { id: "discharge_circuit", name: "Discharge Circuit\n(Active)", type: "safety", stripe: "stripe-new",
    fullName: "Passive Capacitor Energy Bleed",
    duty: "DC-Link Residual Bleeding",
    purpose: "Quickly drains remaining voltage from the inverter capacitors after shutdown to make the system safe for marshals.",
    procurement: 'made',
    cost: 30, dims: "PCB module", product: "Active Discharge Resistor Circuit",
    desc: "NEW: Active discharge circuit. Always active when SDC is open. Discharges DC-link caps to <60V within 5s. Still works if HVD is opened. No fuse in discharge main current path. Not inside TSAC. Typically a power resistor + MOSFET controlled by SDC logic.",
    pins: ["SDC_SIGNAL", "HV_CAP+", "HV_CAP-", "GND"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.mouser.com/c/passive-components/resistors/power-resistors/",
    rules: ["A2.1.1", "A2.3.1", "EV4.9.1", "EV4.9.2", "EV4.9.3", "EV4.9.4", "EV6.1.5", "T11.10.1"],
    isNew: true, newNote: "Engages whenever SDC opens. Discharges TS to <60V in <5s.",
    x: c(3), y: r(8), x3: 0.2, y3: 0.2, z3: 0.8 },

  { id: "data_logger_conn", name: "Data Logger\nConnector (Officials)", type: "module", stripe: "stripe-new",
    fullName: "Official Inspection Interface",
    duty: "Mandatory Regulatory Data Portal",
    purpose: "Provides authorities with access to the car's power delivery stats for during-competition rule compliance monitoring.",
    procurement: 'bought',
    cost: 10, dims: "Panel-mount connector", product: "Panel-Mount Connector for Officials' Logger",
    desc: "NEW: Connector for officials-provided data logger. In negative TS supply path between most-negative AIR and inverters. TS voltage sense connects to most-positive AIR (vehicle side). Accessible within 15min. Not inside TSAC.",
    pins: ["TS_I_IN", "TS_I_OUT", "TS_V_SENSE", "GND"],
    img: "https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/filter/circular-connectors/437",
    rules: ["EV4.6.1", "EV4.6.2", "EV4.6.3", "EV4.6.4", "EV4.6.5"],
    isNew: true, newNote: "Officials' data logger inserted here during competition.",
    x: c(4), y: r(7), x3: 0.3, y3: 0.3, z3: 1.1 },

  { id: "tsmp", name: "TSMP Panel\n(TS Measuring Points)", type: "module", stripe: "stripe-module",
    fullName: "High-Voltage Voltage Test Interface",
    duty: "Safe Manual Potential Verification",
    purpose: "Provides externally accessible terminals for marshals to verify that the TS voltage is safe with a multimeter.",
    procurement: 'made',
    cost: 25, dims: "80×50×30mm", product: "4mm 600V CAT III Banana Jacks + Resistors",
    desc: "FIXED: TS+ and TS- 4mm shrouded banana jacks on ORANGE background, rated ≥600V CAT III. Connected directly to DC-link capacitors (even when HVD open). Current-limiting resistors (10kΩ for 200-400V TS). GND jack (black, 4mm) for LVS ground adjacent. Non-conductive cover, tool-free.",
    pins: ["TS+", "TS-", "GND_JACK"],
    img: "https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/filter/banana-and-tip-connectors-jacks/437",
    rules: ["A2.1.1", "EV4.7.1", "EV4.7.2", "EV4.7.3", "EV4.7.4", "EV4.7.6", "EV4.7.8"],
    isFixed: true, fixNote: "Now includes current-limiting resistors and black GND jack. Mounted next to master switches.",
    x: c(4), y: r(8), x3: 0.35, y3: 0.7, z3: 0 },

  // ── ACTUATORS ─────────────────────────────────────────
  { id: "mosfet_front", name: "Front MOSFET\nDriver", type: "module", stripe: "stripe-module",
    fullName: "Signal Power Amplifier (F)",
    duty: "PWM-to-Brake Load Gateway",
    purpose: "Converts low-logic signals from the ECU into high-current pulses to modulate the front brake solenoids.",
    procurement: 'bought',
    cost: 2.5, dims: "33×24×20mm", product: "IRF520 MOSFET Module",
    desc: "Drives 12V front brake solenoid from ECU 3.3V PWM. PC1→SIG.",
    pins: ["VCC", "GND", "SIG", "VIN", "GND_OUT"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=IRF520+MOSFET+module", rules: ["T11.10", "T11.10.1"],
    x: c(3), y: r(5), x3: 0, y3: 0.3, z3: -0.8 },
  { id: "mosfet_rear", name: "Rear MOSFET\nDriver", type: "module", stripe: "stripe-module",
    fullName: "Signal Power Amplifier (R)",
    duty: "PWM-to-Brake Load Gateway",
    purpose: "Converts low-logic signals from the ECU into high-current pulses to modulate the rear brake solenoids.",
    procurement: 'bought',
    cost: 2.5, dims: "33×24×20mm", product: "IRF520 MOSFET Module",
    desc: "Drives 12V rear brake solenoid from ECU 3.3V PWM. PC2→SIG.",
    pins: ["VCC", "GND", "SIG", "VIN", "GND_OUT"],
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=IRF520+MOSFET+module", rules: ["T11.10", "T11.10.1"],
    x: c(3), y: r(6), x3: 0, y3: 0.3, z3: 0.8 },
  { id: "front_solenoid", name: "Front Brake\nSolenoid Valve", type: "actuator", stripe: "stripe-actuator",
    fullName: "Hydraulic Pulsation Modulator (F)",
    duty: "Dynamic Brake Force Regulation",
    purpose: "Mechanically gates hydraulic pressure to the front calipers for active torque management or slip pulses.",
    procurement: 'bought',
    cost: 25.5, dims: "60×40×30mm", product: "12V NC Solenoid Valve",
    desc: "12V normally-closed solenoid valve for front brake pulsation (ABS-like). Driven via MOSFET driver from ECU PWM.",
    pins: ["V+", "GND"],
    img: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=12V+normally+closed+solenoid+valve", rules: ["T11.10", "T11.10.1"],
    x: c(2), y: r(5), x3: 0, y3: 0.2, z3: -0.9 },
  { id: "rear_solenoid", name: "Rear Brake\nSolenoid Valve", type: "actuator", stripe: "stripe-actuator",
    fullName: "Hydraulic Pulsation Modulator (R)",
    duty: "Dynamic Brake Force Regulation",
    purpose: "Mechanically gates hydraulic pressure to the rear calipers to achieve pitch stability during hard deceleration.",
    procurement: 'bought',
    cost: 25.5, dims: "60×40×30mm", product: "12V NC Solenoid Valve",
    desc: "12V normally-closed solenoid valve for rear brake pulsation. Driven via MOSFET driver from ECU PWM.",
    pins: ["V+", "GND"],
    img: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=12V+normally+closed+solenoid+valve", rules: ["T11.10", "T11.10.1"],
    x: c(2), y: r(6), x3: 0, y3: 0.2, z3: 0.9 },

  // ── INDICATORS (HARDWARE-DRIVEN) ─────────────────────
  { id: "tsal_hw", name: "TSAL\n(Hardware Circuit)", type: "safety", stripe: "stripe-new",
    fullName: "Tractive System Active Light Controller",
    duty: "Safety Visualization Logic",
    purpose: "Team-designed indicator controller. Hard-wired electronics that manage the Red (energized) and Green (safe) light states (EV4.10).",
    procurement: 'made',
    cost: 45, dims: "90×70×30mm", product: "Team-Designed TSAL Logic Circuit",
    desc: "Safety Beacon Driver. Hardwired electronics (no software, EV4.10.9). Independent Red/Green circuits. Red flashes 2-5Hz when >60VDC detected on DC-link. Green stays ON when AIRs open and TS safe. Failsafes built into analog logic.",
    pins: ["RED_HW+", "GRN_HW+", "GND", "VS_MEAS", "RELAY_STATUS"],
    img: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.mouser.com/c/semiconductors/timers-oscillators/",
    rules: ["A2.1.1", "A2.3.1", "EV4.10.1", "EV4.10.2", "EV4.10.3", "EV4.10.4", "EV4.10.6", "EV4.10.9", "T11.10.1"],
    isNew: true, newNote: "All TSAL logic is hardwired electronics. No software control. Red and green circuits are fully independent.",
    x: c(8), y: r(3), x3: 0, y3: 0.9, z3: 0.15 },

  { id: "cockpit_panel", name: "Cockpit Panel\n(HW-Driven Indicators)", type: "display", stripe: "stripe-new",
    fullName: "Auxiliary Driver Status Panel",
    duty: "Fault Notification Aggregation",
    purpose: "Provides hardware-driven visual alerts for critical faults (IMD, AMS) that must remain visible if the ECU fails.",
    procurement: 'made',
    cost: 20, dims: "100×60×20mm", product: "Panel with Hardwired LEDs",
    desc: "NEW/FIXED: Indicators now hardware-driven (not ECU). Contains: TS-OFF green (from TSAL HW circuit), IMD-FAULT red (from IMD directly), AMS-FAULT red (from AMS directly). All latch on until manual reset per EV6.1.6. R2D start button also on this panel.",
    pins: ["TS_OFF_IN_HW", "IMD_FAULT_IN_HW", "AMS_FAULT_IN_HW", "RTD_BTN_OUT", "GND"],
    img: "https://images.unsplash.com/photo-1542362567-b05500c5e156?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A - Custom Assembly",
    rules: ["A2.1.1", "EV4.10.10", "EV5.8.9", "EV6.3.8", "EV6.1.6"],
    isNew: true, newNote: "IMD, AMS, TSAL indicator signals all from hardware sources. Includes R2D button.",
    x: c(8), y: r(5), x3: 0, y3: 0.65, z3: -0.45 },

  { id: "tsal_light", name: "TSAL Light\n(External)", type: "display", stripe: "stripe-display",
    fullName: "High-Visibility Safety Beacon",
    duty: "Visual State Exposure",
    purpose: "The physical light beacon visible to marshals to confirm if the TS is currently energized.",
    procurement: 'bought',
    cost: 30, dims: "80×80×50mm", product: "High-Brightness Red/Green LED Array",
    desc: "Physical TSAL light visible externally. Driven by TSAL HW circuit. Located ≥75mm below main hoop top, within rollover envelope. Visible from 1.6m height, 3m radius, direct sunlight.",
    pins: ["RED+", "GRN+", "GND"],
    img: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.mouser.com/c/optoelectronics/led-lighting/led-modules/",
    rules: ["EV4.10.7", "EV4.10.8"],
    x: c(8), y: r(4), x3: 0, y3: 1.0, z3: 0.15 },

  { id: "brake_light", name: "Brake Light\n(Mandatory)", type: "display", stripe: "stripe-new",
    fullName: "Rear External Stop Indicator",
    duty: "Deceleration Notification",
    purpose: "Alerts following vehicles and track-side personnel when the car is applying hydraulic or regenerative braking.",
    procurement: 'bought',
    cost: 15, dims: "150×50×30mm", product: "Red LED Brake Light ≥15000mcd",
    desc: "NEW: Mandatory. Illuminated if hydraulic or electric brake is applied. ≥15000mcd brightness, ≥15cm² illuminated area, vertical mounting ≥250mm from ground, visible from rear. Driven by ECU PC3 based on Front (FBPS) AND Rear (RBPS) circuit pressures.",
    pins: ["V+", "GND", "SIGNAL_IN"],
    img: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.amazon.com/s?k=LED+brake+light+15000mcd",
    rules: ["T6.3.1", "T6.3.2", "T6.3.3"],
    isNew: true, newNote: "Driven by ECU PC3 (digital output based on OR logic of front/rear pressure sensors).",
    x: c(8), y: r(6), x3: 0, y3: 0.4, z3: 1.5 },

  { id: "rtd_sound", name: "R2D Buzzer\n(Ready-To-Drive)", type: "display", stripe: "stripe-new",
    fullName: "Ready-to-Drive Warning Speaker",
    duty: "Audible Mode Transition Notification",
    purpose: "Sounds the mandatory alarm to warn people that the motors are about to become active and capable of movement.",
    procurement: 'bought',
    cost: 10, dims: "40×40×20mm", product: "80-90dBA Buzzer / Piezo Speaker",
    desc: "NEW: Mandatory. Sounds for 1-3s when entering R2D mode. 80-90dBA within 2m. Triggered by ECU when: driver presses R2D button while brake applied + TS active + SDC closed. Must be easily recognizable sound.",
    pins: ["V+", "GND", "SIGNAL"],
    img: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.digikey.com/en/products/filter/buzzers-transducers-electronic/157",
    rules: ["EV4.12.1", "EV4.12.2", "EV4.12.3", "EV4.11.7"],
    isNew: true, newNote: "ECU PC4 drives R2D buzzer. R2D state machine in firmware: brake pressed + button press = R2D mode.",
    x: c(8), y: r(7), x3: 0, y3: 0.2, z3: -0.6 },

  { id: "dc_link", name: "DC-Link Caps\n(Vehicle Side)", type: "module", stripe: "stripe-power",
    fullName: "Inverter Buffer Reservoir",
    duty: "Voltage Ripple Suppression",
    purpose: "Acts as a high-capacity buffer for the tractive system, serving as the source for discharge and TSAL voltage measurement.",
    cost: 0, dims: "N/A", product: "Inverter Intermediate Circuit",
    desc: "VIRTUAL NODE: The Intermediate Circuit capacitors. Rule EV4.7.2: TSMP must be directly connected here. Rule EV4.9: Discharge circuit monitors these. Rule EV4.10: TSAL monitors these.",
    pins: ["HV+", "HV-"], img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A", rules: ["EV4.7.2", "EV4.9", "EV4.10"], isNew: false,
    x: c(6), y: r(1), x3: 0, y3: 0.3, z3: 0.9 },

  { id: "motor_controller", name: "Inverter / MC\n(Motor Controller)", type: "actuator", stripe: "stripe-safety",
    fullName: "High-Voltage Traction Inverter",
    duty: "TS Energy Modulation",
    purpose: "Converts DC battery power to 3-phase AC for the motor based on CAN torque requests from the ECU.",
    procurement: 'bought',
    cost: 850, dims: "200×150×80mm", product: "BorgWarner / Cascadia PM100",
    desc: "Main traction inverter. Receives HV power from AIRs. Controlled via CAN. Rule T11.9.4: Watchdog must disable torque if CAN link lost for >500ms. Active discharge integrated.",
    pins: ["HV+", "HV-", "CANH", "CANL", "PHASE_A", "PHASE_B", "PHASE_C"],
    img: "https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "https://www.cascadiamotion.com/products/all-products",
    rules: ["T11.9.4", "EV4.9", "EV5.6"],
    x: c(6), y: r(4), x3: 0.1, y3: 0.2, z3: 1.0 },

  { id: "chassis_gnd_hoop", name: "Chassis Ground\n(Main Hoop)", type: "module", stripe: "stripe-module",
    fullName: "Structure Potential Reference",
    duty: "Isolation Measurement Anchor",
    purpose: "The primary chassis grounding point for IMD insulation monitoring within the driver compartment.",
    cost: 0, dims: "Bolt mount", product: "Steel Chassis Point",
    desc: "Rule EV6.3.6: Second chassis ground measurement line for IMD. Must be a separate conductor rated for max TS voltage.",
    pins: ["GND"], img: "https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A", rules: ["EV6.3.6"], isNew: false,
    x: c(6), y: r(10), x3: 0, y3: 0.1, z3: 0.15 },

  { id: "chassis_gnd_tsac", name: "Chassis Ground\n(TSAC Enclosure)", type: "module", stripe: "stripe-module",
    fullName: "Accumulator Potential Reference",
    duty: "Enclosure Equipotential Bonding",
    purpose: "Ensures the accumulator enclosure is at the same potential as the chassis to avoid ground loops and shock risks.",
    cost: 0, dims: "Bolt mount", product: "Aluminium TSAC Point",
    desc: "Rule EV6.3.6: First chassis ground measurement line for IMD. Must be a separate conductor rated for max TS voltage.",
    pins: ["GND"], img: "https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=300&h=200",
    buy: "N/A", rules: ["EV6.3.6"], isNew: false,
    x: c(7), y: r(10), x3: 0, y3: 0.1, z3: 1.0 },
];

export const EDGES: Edge[] = [
  // ── 12V POWER ──────────────────────────────────────
  { s: "main_battery", t: "lvms", cls: "edge-12v", lbl: "12V (LV, non-orange)" },
  { s: "lvms", t: "pdu", cls: "edge-12v", lbl: "12V from LVMS" },
  { s: "lvms", t: "bspd", cls: "edge-12v", lbl: "12V DIRECT (T11.6.3)" },
  { s: "pdu", t: "buck5v", cls: "edge-12v", lbl: "12V to Buck" },
  { s: "pdu", t: "mosfet_front", cls: "edge-12v", lbl: "12V" },
  { s: "pdu", t: "mosfet_rear", cls: "edge-12v", lbl: "12V" },
  { s: "pdu", t: "airs", cls: "edge-12v", lbl: "AIR Coil Drive" },

  // ── 5V POWER ────────────────────────────────────────
  { s: "buck5v", t: "main_ecu", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "can_xcvr", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "driver_display", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "fl_wss", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "fr_wss", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rl_wss", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rr_wss", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "apps1", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "apps2", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "steer_sensor", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "fbps", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rbps", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "fl_susp", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "fr_susp", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rl_susp", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rr_susp", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "ts_current", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "imd", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "tsal_hw", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "cockpit_panel", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "brake_light", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "rtd_sound", cls: "edge-5v", lbl: "5V" },
  { s: "buck5v", t: "tsmp", cls: "edge-5v", lbl: "5V (GND ref)" },
  { s: "buck5v", t: "data_logger_conn", cls: "edge-5v", lbl: "5V" },

  // ── CAN BUS ─────────────────────────────────────────
  { s: "main_ecu", t: "can_xcvr", cls: "edge-can", lbl: "CAN1 RX/TX (PB8/PB9)" },
  { s: "can_xcvr", t: "driver_display", cls: "edge-can", lbl: "CAN Bus H/L" },
  { s: "can_xcvr", t: "ams", cls: "edge-can", lbl: "CAN Bus H/L" },
  { s: "can_xcvr", t: "motor_controller", cls: "edge-can", lbl: "CAN Bus (Torque Cmd)" },

  // ── SENSOR → ECU ANALOG/DIGITAL ─────────────────────
  { s: "fl_wss", t: "main_ecu", cls: "edge-analog", lbl: "Pulse→PA0" },
  { s: "fr_wss", t: "main_ecu", cls: "edge-analog", lbl: "Pulse→PA1" },
  { s: "rl_wss", t: "main_ecu", cls: "edge-analog", lbl: "Pulse→PA2" },
  { s: "rr_wss", t: "main_ecu", cls: "edge-analog", lbl: "Pulse→PA3" },
  { s: "apps1", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PA4 (SCS)" },
  { s: "apps2", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PA5 (SCS)" },
  { s: "steer_sensor", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PA6" },
  { s: "fbps", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PA7" },
  { s: "rbps", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PB0" },
  { s: "fl_susp", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PB1" },
  { s: "fr_susp", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PB2" },
  { s: "rl_susp", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PB3" },
  { s: "rr_susp", t: "main_ecu", cls: "edge-analog", lbl: "Analog→PC0" },

  // ── BSPD DIRECT SENSOR INPUTS (bypass ECU) ──────────
  { s: "fbps", t: "bspd", cls: "edge-analog", lbl: "BPS_IN direct (T11.6.4)" },
  { s: "ts_current", t: "bspd", cls: "edge-analog", lbl: "CURRENT_IN direct" },

  // ── IMD → ECU (telemetry only, not SDC) ─────────────
  { s: "imd", t: "main_ecu", cls: "edge-i2c", lbl: "SDA/SCL PB6/PB7 (data log only)" },

  // ── ECU PWM OUTPUTS ─────────────────────────────────
  { s: "main_ecu", t: "mosfet_front", cls: "edge-pwm", lbl: "PWM PC1→SIG" },
  { s: "main_ecu", t: "mosfet_rear", cls: "edge-pwm", lbl: "PWM PC2→SIG" },
  { s: "mosfet_front", t: "front_solenoid", cls: "edge-pwm", lbl: "Switched 12V" },
  { s: "mosfet_rear", t: "rear_solenoid", cls: "edge-pwm", lbl: "Switched 12V" },

  // ── ECU DIGITAL OUTPUTS ─────────────────────────────
  { s: "main_ecu", t: "brake_light", cls: "edge-digital", lbl: "PC3 brake signal" },
  { s: "main_ecu", t: "rtd_sound", cls: "edge-digital", lbl: "PC4 R2D trigger" },
  { s: "cockpit_panel", t: "main_ecu", cls: "edge-digital", lbl: "R2D_BTN→PC5" },

  // ── TSAL HW CIRCUIT ─────────────────────────────────
  { s: "tsal_hw", t: "tsal_light", cls: "edge-digital", lbl: "HW RED/GRN drive" },
  { s: "tsal_hw", t: "cockpit_panel", cls: "edge-digital", lbl: "TS_OFF HW signal" },

  // ── HARDWARE SHUTDOWN CIRCUIT (SDC) ─────────────────
  // Order: LVMS -> Safety Logic (BSPD, BOTS, IMD, AMS) -> Switches -> TSMS -> PDU (AIR)
  { s: "lvms", t: "bspd", cls: "edge-sdc", lbl: "SDC Start (LVMS Out)" },
  { s: "bspd", t: "bots", cls: "edge-sdc", lbl: "SDC (BSPD→BOTS)" },
  { s: "bots", t: "e_stop_cockpit", cls: "edge-sdc", lbl: "SDC (BOTS→Cockpit)" },
  { s: "e_stop_cockpit", t: "e_stop_ext_l", cls: "edge-sdc", lbl: "SDC Chain" },
  { s: "e_stop_ext_l", t: "e_stop_ext_r", cls: "edge-sdc", lbl: "SDC Chain" },
  { s: "e_stop_ext_r", t: "inertia", cls: "edge-sdc", lbl: "SDC Chain" },
  { s: "inertia", t: "hvd", cls: "edge-sdc", lbl: "SDC→HVD Interlock" },
  { s: "hvd", t: "imd", cls: "edge-sdc", lbl: "SDC interlock" },
  { s: "imd", t: "ams", cls: "edge-sdc", lbl: "SDC Series Loop (IMD hw contact breaks SDC directly)" },
  { s: "imd", t: "ams", cls: "edge-can", lbl: "Diag State Interface (tells AMS computer IMD has tripped)" },
  { s: "ams", t: "tsms", cls: "edge-sdc", lbl: "SDC Series Loop (Hardware loop wire connects to TSMS mechanical contacts)" },
  { s: "tsms", t: "pdu", cls: "edge-sdc", lbl: "SDC Series Loop (TSMS contacts to AIR Relay in PDU)" },

  // Hardware Indicator signals (IMD/AMS direct to cockpit, bypass ECU)
  { s: "imd", t: "cockpit_panel", cls: "edge-digital", lbl: "IMD_FAULT HW (Direct)" },
  { s: "ams", t: "cockpit_panel", cls: "edge-digital", lbl: "AMS_FAULT HW (Direct)" },

  // Tractive System Measurements (Reference connections for perfection)
  { s: "airs", t: "dc_link", cls: "edge-hw", lbl: "HV Power Path" },
  { s: "dc_link", t: "motor_controller", cls: "edge-hw", lbl: "TS Power to Inverter" },
  { s: "dc_link", t: "tsmp", cls: "edge-hw", lbl: "TS Measuring Path (EV4.7.2)" },
  { s: "dc_link", t: "tsal_hw", cls: "edge-hw", lbl: "TSAL Voltage Check (Independent)" },
  { s: "dc_link", t: "discharge_circuit", cls: "edge-hw", lbl: "Active Discharge Path" },

  // IMD Chassis Grounds (EV6.3.6)
  { s: "imd", t: "chassis_gnd_hoop", cls: "edge-hw", lbl: "GND Meas Line 1 (Main Hoop)" },
  { s: "imd", t: "chassis_gnd_tsac", cls: "edge-hw", lbl: "GND Meas Line 2 (TSAC)" },

  // ── PEDAL & HARNESS INTEGRATION ─────────────────────
  { s: "pedal_box", t: "apps1", cls: "edge-hw", lbl: "Throttle Link" },
  { s: "pedal_box", t: "apps2", cls: "edge-hw", lbl: "Throttle Link" },
  { s: "pedal_box", t: "fbps", cls: "edge-hw", lbl: "Hydraulic Pressure (Front)" },
  { s: "pedal_box", t: "rbps", cls: "edge-hw", lbl: "Hydraulic Pressure (Rear)" },
  { s: "pedal_box", t: "bots", cls: "edge-hw", lbl: "Brake Over-Travel Link" },
  { s: "main_battery", t: "lv_harness", cls: "edge-12v", lbl: "Main Power Entry" },
  { s: "lv_harness", t: "lvms", cls: "edge-12v", lbl: "Primary Loom" },
];
